# Use the official Node.js image as base
FROM node:18

# Set the default working directory
WORKDIR /usr/src/app

# This image will run dynamic user code passed via volume mount
CMD ["node", "/usr/src/app/userCode.js"]
